In [82]:
!pip3 install openpyxl pandas langchain langchain-openai langchain-ollama python-dotenv

from context_processing.col_row_context import col_based_processing, row_based_processing
from context_processing.raw_dump import get_read_data
from context_processing.inverted_index import build_inverted_index
from typing import Union


import openpyxl
import json
import pandas as pd
from llm_util import call_llm
def get_data(path="all_data_912/dataset.json"):
    df=pd.read_json(path)
    return df
# given a context it should give a respone
def eval(context):
    prompt=f"Given the context {context}, answer the question"
    response=call_llm(prompt)
    return response
def list_sheets(path: str):
    wb = openpyxl.load_workbook(path, data_only=True)
    return wb.sheetnames
def make_context(spreadsheet_path,sheet_name:Union[int,str,None]=None,type="col"):
    try:
    
        if sheet_name is None:
            sheets=list_sheets(spreadsheet_path)
        else :
            sheets=[sheet_name]
        context={}
        for sheet in sheets:
            if type=="col":
                context[sheet]= col_based_processing(spreadsheet_path,sheet)
            elif type=="row":
                context[sheet]= row_based_processing(spreadsheet_path,sheet)
            elif type=="inverted":
                context[sheet]= build_inverted_index(spreadsheet_path,sheet)
            elif type=="raw":
                context[sheet]= get_read_data(spreadsheet_path,sheet)
    except Exception as e:
        return None
    return context
# different benchmarks for col/row/inverted/raw
# shuld have a feature for single llm or multiple llms evaluation


def eval_benchmark():
    df=get_data()
    df['context']=df['spreadsheet_path'].apply(make_context)
    df['eval_response']=df['context'].apply(eval)
    df['answer_correctness']= df.apply(lambda row: row['eval_response'].strip().lower() == row['answer'].strip().lower(), axis=1)
    return df

Requirement already satisfied: openpyxl in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (3.1.5)
Requirement already satisfied: pandas in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: langchain in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (0.3.27)
Requirement already satisfied: langchain-openai in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (0.3.33)
Requirement already satisfied: langchain-ollama in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (0.3.8)
Requirement already satisfied: python-dotenv in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (1.0.1)
Requirement already satisfied: et-xmlfile in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: numpy>=1.22.4 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from pandas) (2025.1)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.72 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain) (0.3.76)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain) (0.3.11)
Requirement already satisfied: langsmith>=0.1.17 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain) (0.4.29)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain) (2.10.5)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain) (1.4.54)
Requirement already satisfied: requests<3,>=2 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain) (2.32.5)
Requirement already satisfied: PyYAML>=5.3 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain) (6.0.1)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain) (4.0.3)
Requirement already satisfied: openai<2.0.0,>=1.104.2 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain-openai) (1.108.1)
Requirement already satisfied: tiktoken<1,>=0.7 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain-openai) (0.11.0)
Requirement already satisfied: ollama<1.0.0,>=0.5.3 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain-ollama) (0.5.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (9.0.0)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (1.33)
Requirement already satisfied: typing-extensions>=4.7 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (4.14.1)
Requirement already satisfied: packaging>=23.2 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (24.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langsmith>=0.1.17->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langsmith>=0.1.17->langchain) (3.11.3)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langsmith>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from langsmith>=0.1.17->langchain) (0.25.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from openai<2.0.0,>=1.104.2->langchain-openai) (4.8.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from openai<2.0.0,>=1.104.2->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from openai<2.0.0,>=1.104.2->langchain-openai) (0.10.0)
Requirement already satisfied: sniffio in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from openai<2.0.0,>=1.104.2->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from openai<2.0.0,>=1.104.2->langchain-openai) (4.67.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.27.2)
Requirement already satisfied: six>=1.5 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from requests<3,>=2->langchain) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from requests<3,>=2->langchain) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from requests<3,>=2->langchain) (2024.12.14)
Requirement already satisfied: regex>=2022.1.18 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from tiktoken<1,>=0.7->langchain-openai) (2024.11.6)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from anyio<5,>=3.5.0->openai<2.0.0,>=1.104.2->langchain-openai) (1.2.2)
Requirement already satisfied: httpcore==1.* in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.72->langchain) (3.0.0)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [83]:
print(make_context("test.xlsx",type="row"))
with open("eval_output.json", "w") as f:
    json.dump(make_context("test.xlsx"), f, indent=2)

{'Export Summary': '|A1, None, empty| |B1, None, empty| |C1, None, empty| |D1, None, empty| || |A2, None, empty| |B2, None, empty| |C2, None, empty| |D2, None, empty| || |A3, None, empty| |B3, This document was exported from Numbers.  Each table was converted to an Excel worksheet. All other objects on each Numbers sheet were placed on separate worksheets. Please be aware that formula calculations may differ in Excel., string| |C3, None, empty| |D3, None, empty| || |A4, None, empty| |B4, None, empty| |C4, None, empty| |D4, None, empty| || |A5, None, empty| |B5, None, empty| |C5, None, empty| |D5, None, empty| || |A6, None, empty| |B6, None, empty| |C6, None, empty| |D6, None, empty| || |A7, None, empty| |B7, Numbers Sheet Name, string| |C7, Numbers Table Name, string| |D7, Excel Worksheet Name, string| || |A8, None, empty| |B8, None, empty| |C8, None, empty| |D8, None, empty| || |A9, None, empty| |B9, Salary List, string| |C9, None, empty| |D9, None, empty| || |A10, None, empty| |B10, None, empty| |C10, Table 1, string| |D10, Salary List, string| || |A11, None, empty| |B11, Blacklist, string| |C11, None, empty| |D11, None, empty| || |A12, None, empty| |B12, None, empty| |C12, Table 1, string| |D12, Blacklist, string|', 'Salary List': '|A1, Company / Role, string| |B1, Bye World, string| |C1, Benefits, string| |D1, Year, string| |E1, Position, string| |F1, None, empty| |G1, None, empty| |H1, None, empty| |I1, None, empty| |J1, None, empty| |K1, None, empty| |L1, None, empty| |M1, None, empty| |N1, None, empty| |O1, None, empty| |P1, None, empty| |Q1, None, empty| |R1, None, empty| |S1, None, empty| |T1, None, empty| |U1, None, empty| |V1, None, empty| |W1, None, empty| |X1, None, empty| |Y1, None, empty| || |A2, 1password, string| |B2, 50/hr (4th coop), string| |C2, None, empty| |D2, 2023, number| |E2, None, empty| |F2, None, empty| |G2, None, empty| |H2, None, empty| |I2, None, empty| |J2, None, empty| |K2, None, empty| |L2, None, empty| |M2, None, empty| |N2, None, empty| |O2, None, empty| |P2, None, empty| |Q2, None, empty| |R2, None, empty| |S2, None, empty| |T2, None, empty| |U2, None, empty| |V2, None, empty| |W2, None, empty| |X2, None, empty| |Y2, None, empty| || |A3, Abbott ADD, string| |B3, 22.05/hr (2nd coop), string| |C3, None, empty| |D3, None, empty| |E3, None, empty| |F3, None, empty| |G3, None, empty| |H3, None, empty| |I3, None, empty| |J3, None, empty| |K3, None, empty| |L3, None, empty| |M3, None, empty| |N3, None, empty| |O3, None, empty| |P3, None, empty| |Q3, None, empty| |R3, None, empty| |S3, None, empty| |T3, None, empty| |U3, None, empty| |V3, None, empty| |W3, None, empty| |X3, None, empty| |Y3, None, empty| || |A4, Abnormal Security, string| |B4, 106k USD annual prorated (~$51/hr USD), string| |C4, 5k relocation, string| |D4, None, empty| |E4, None, empty| |F4, None, empty| |G4, None, empty| |H4, None, empty| |I4, None, empty| |J4, None, empty| |K4, None, empty| |L4, None, empty| |M4, None, empty| |N4, None, empty| |O4, None, empty| |P4, None, empty| |Q4, None, empty| |R4, None, empty| |S4, None, empty| |T4, None, empty| |U4, None, empty| |V4, None, empty| |W4, None, empty| |X4, None, empty| |Y4, None, empty| || |A5, Accedo, string| |B5, 25-27/hr (3rd coop), string| |C5, None, empty| |D5, None, empty| |E5, None, empty| |F5, None, empty| |G5, None, empty| |H5, None, empty| |I5, None, empty| |J5, None, empty| |K5, None, empty| |L5, None, empty| |M5, None, empty| |N5, None, empty| |O5, None, empty| |P5, None, empty| |Q5, None, empty| |R5, None, empty| |S5, None, empty| |T5, None, empty| |U5, None, empty| |V5, None, empty| |W5, None, empty| |X5, None, empty| |Y5, None, empty| || |A6, None, empty| |B6, 20-25/hr, string| |C6, None, empty| |D6, None, empty| |E6, None, empty| |F6, None, empty| |G6, None, empty| |H6, None, empty| |I6, None, empty| |J6, None, empty| |K6, None, empty| |L6, None, empty| |M6, None, empty| |N6, None, empty| |O6, None, empty| |P6, None, empty| |Q6, None, empty| |R6, None, empty| |S6, None, empty| |T6, None, empty| |U6, None, empty| |V6, None, empty| |W6, None, empty| |X6, None, empty| |Y6, None, empty| || |A7, Addepar, string| |B7, 40/hr, 48/hr (5th coop), string| |C7, None, empty| |D7, None, empty| |E7, None, empty| |F7, None, empty| |G7, None, empty| |H7, None, empty| |I7, None, empty| |J7, None, empty| |K7, None, empty| |L7, None, empty| |M7, None, empty| |N7, None, empty| |O7, None, empty| |P7, None, empty| |Q7, None, empty| |R7, None, empty| |S7, None, empty| |T7, None, empty| |U7, None, empty| |V7, None, empty| |W7, None, empty| |X7, None, empty| |Y7, None, empty| || |A8, AdHawk Microsystems, string| |B8, 40/hr (5th coop), string| |C8, None, empty| |D8, 2024, number| |E8, Algorithms Developer, string| |F8, None, empty| |G8, None, empty| |H8, None, empty| |I8, None, empty| |J8, None, empty| |K8, None, empty| |L8, None, empty| |M8, None, empty| |N8, None, empty| |O8, None, empty| |P8, None, empty| |Q8, None, empty| |R8, None, empty| |S8, None, empty| |T8, None, empty| |U8, None, empty| |V8, None, empty| |W8, None, empty| |X8, None, empty| |Y8, None, empty| || |A9, None, empty| |B9, less than 44/hr, string| |C9, None, empty| |D9, None, empty| |E9, None, empty| |F9, None, empty| |G9, None, empty| |H9, None, empty| |I9, None, empty| |J9, None, empty| |K9, None, empty| |L9, None, empty| |M9, None, empty| |N9, None, empty| |O9, None, empty| |P9, None, empty| |Q9, None, empty| |R9, None, empty| |S9, None, empty| |T9, None, empty| |U9, None, empty| |V9, None, empty| |W9, None, empty| |X9, None, empty| |Y9, None, empty| || |A10, AGF Investments, string| |B10, 25/hr (2nd coop), string| |C10, None, empty| |D10, 2023, number| |E10, Web Developer (Junior), string| |F10, None, empty| |G10, None, empty| |H10, None, empty| |I10, None, empty| |J10, None, empty| |K10, None, empty| |L10, None, empty| |M10, None, empty| |N10, None, empty| |O10, None, empty| |P10, None, empty| |Q10, None, empty| |R10, None, empty| |S10, None, empty| |T10, None, empty| |U10, None, empty| |V10, None, empty| |W10, None, empty| |X10, None, empty| |Y10, None, empty| || |A11, AI Arena, string| |B11, 45/hr, string| |C11, None, empty| |D11, None, empty| |E11, None, empty| |F11, None, empty| |G11, None, empty| |H11, None, empty| |I11, None, empty| |J11, None, empty| |K11, None, empty| |L11, None, empty| |M11, None, empty| |N11, None, empty| |O11, None, empty| |P11, None, empty| |Q11, None, empty| |R11, None, empty| |S11, None, empty| |T11, None, empty| |U11, None, empty| |V11, None, empty| |W11, None, empty| |X11, None, empty| |Y11, None, empty| || |A12, Akuna Capital, string| |B12, 65 USD/hour, string| |C12, return flight + corporate housing, string| |D12, None, empty| |E12, None, empty| |F12, None, empty| |G12, None, empty| |H12, None, empty| |I12, None, empty| |J12, None, empty| |K12, None, empty| |L12, None, empty| |M12, None, empty| |N12, None, empty| |O12, None, empty| |P12, None, empty| |Q12, None, empty| |R12, None, empty| |S12, None, empty| |T12, None, empty| |U12, None, empty| |V12, None, empty| |W12, None, empty| |X12, None, empty| |Y12, None, empty| || |A13, Altice USA, string| |B13, mid 30s/hr (6th coop), string| |C13, None, empty| |D13, None, empty| |E13, None, empty| |F13, None, empty| |G13, None, empty| |H13, None, empty| |I13, None, empty| |J13, None, empty| |K13, None, empty| |L13, None, empty| |M13, None, empty| |N13, None, empty| |O13, None, empty| |P13, None, empty| |Q13, None, empty| |R13, None, empty| |S13, None, empty| |T13, None, empty| |U13, None, empty| |V13, None, empty| |W13, None, empty| |X13, None, empty| |Y13, None, empty| || |A14, Amazon, string| |B14, 9138 USD/month, string| |C14, 2425/month tax-free relocation stipend, string| |D14, None, empty| |E14, None, empty| |F14, None, empty| |G14, None, empty| |H14, None, empty| |I14, None, empty| |J14, None, empty| |K14, None, empty| |L14, None, empty| |M14, None, empty| |N14, None, empty| |O14, None, empty| |P14, None, empty| |Q14, None, empty| |R14, None, empty| |S14, None, empty| |T14, None, empty| |U14, None, empty| |V14, None, empty| |W14, None, empty| |X14, None, empty| |Y14, None, empty| || |A15, AMD, string| |B15, 27/hr, ~21.88/hr (4th coop), ~29.33/hr (6th coop), string| |C15, None, empty| |D15, None, empty| |E15, None, empty| |F15, None, empty| |G15, None, empty| |H15, None, empty| |I15, None, empty| |J15, None, empty| |K15, None, empty| |L15, None, empty| |M15, None, empty| |N15, None, empty| |O15, None, empty| |P15, None, empty| |Q15, None, empty| |R15, None, empty| |S15, None, empty| |T15, None, empty| |U15, None, empty| |V15, None, empty| |W15, None, empty| |X15, None, empty| |Y15, None, empty| || |A16, American Express, string| |B16, 34.5/hr, string| |C16, None, empty| |D16, None, empty| |E16, None, empty| |F16, None, empty| |G16, None, empty| |H16, None, empty| |I16, None, empty| |J16, None, empty| |K16, None, empty| |L16, None, empty| |M16, None, empty| |N16, None, empty| |O16, None, empty| |P16, None, empty| |Q16, None, empty| |R16, None, empty| |S16, None, empty| |T16, None, empty| |U16, None, empty| |V16, None, empty| |W16, None, empty| |X16, None, empty| |Y16, None, empty| || |A17, ANSYS, string| |B17, math coop average + 10%, string| |C17, None, empty| |D17, None, empty| |E17, None, empty| |F17, None, empty| |G17, None, empty| |H17, None, empty| |I17, None, empty| |J17, None, empty| |K17, None, empty| |L17, None, empty| |M17, None, empty| |N17, None, empty| |O17, None, empty| |P17, None, empty| |Q17, None, empty| |R17, None, empty| |S17, None, empty| |T17, None, empty| |U17, None, empty| |V17, None, empty| |W17, None, empty| |X17, None, empty| |Y17, None, empty| || |A18, None, empty| |B18, (34/hr + 1300-1500 stipend/month), (37/hr + 1350 stipend for 3A term), (44/h + housing or 1k stipend. 4A Product Design), string| |C18, Stipends listed, string| |D18, None, empty| |E18, None, empty| |F18, None, empty| |G18, None, empty| |H18, None, empty| |I18, None, empty| |J18, None, empty| |K18, None, empty| |L18, None, empty| |M18, None, empty| |N18, None, empty| |O18, None, empty| |P18, None, empty| |Q18, None, empty| |R18, None, empty| |S18, None, empty| |T18, None, empty| |U18, None, empty| |V18, None, empty| |W18, None, empty| |X18, None, empty| |Y18, None, empty| || |A19, Apple, string| |B19, 42/hr USD (3A), string| |C19, 3335/mo pretax relocation (3A), string| |D19, 2024, number| |E19, Hardware, string| |F19, None, empty| |G19, None, empty| |H19, None, empty| |I19, None, empty| |J19, None, empty| |K19, None, empty| |L19, None, empty| |M19, None, empty| |N19, None, empty| |O19, None, empty| |P19, None, empty| |Q19, None, empty| |R19, None, empty| |S19, None, empty| |T19, None, empty| |U19, None, empty| |V19, None, empty| |W19, None, empty| |X19, None, empty| |Y19, None, empty| || |A20, Apple, string| |B20, 42/hr USD, string| |C20, 1k/mo stipend, string| |D20, 2024, number| |E20, System Level Test Engineer, string| |F20, None, empty| |G20, None, empty| |H20, None, empty| |I20, None, empty| |J20, None, empty| |K20, None, empty| |L20, None, empty| |M20, None, empty| |N20, None, empty| |O20, None, empty| |P20, None, empty| |Q20, None, empty| |R20, None, empty| |S20, None, empty| |T20, None, empty| |U20, None, empty| |V20, None, empty| |W20, None, empty| |X20, None, empty| |Y20, None, empty| || |A21, Arctic Wolf, string| |B21, 36/hr (3rd coop), 42/hr (4th coop), string| |C21, None, empty| |D21, 2023, number| |E21, None, empty| |F21, None, empty| |G21, None, empty| |H21, None, empty| |I21, None, empty| |J21, None, empty| |K21, None, empty| |L21, None, empty| |M21, None, empty| |N21, None, empty| |O21, None, empty| |P21, None, empty| |Q21, None, empty| |R21, None, empty| |S21, None, empty| |T21, None, empty| |U21, None, empty| |V21, None, empty| |W21, None, empty| |X21, None, empty| |Y21, None, empty| || |A22, Arctic Wolf, string| |B22, 38/hr (4th coop), string| |C22, None, empty| |D22, 2024, number| |E22, None, empty| |F22, None, empty| |G22, None, empty| |H22, None, empty| |I22, None, empty| |J22, None, empty| |K22, None, empty| |L22, None, empty| |M22, None, empty| |N22, None, empty| |O22, None, empty| |P22, None, empty| |Q22, None, empty| |R22, None, empty| |S22, None, empty| |T22, None, empty| |U22, None, empty| |V22, None, empty| |W22, None, empty| |X22, None, empty| |Y22, None, empty| || |A23, Aterlo Networks, string| |B23, 30/hr (4th coop), string| |C23, None, empty| |D23, None, empty| |E23, None, empty| |F23, None, empty| |G23, None, empty| |H23, None, empty| |I23, None, empty| |J23, None, empty| |K23, None, empty| |L23, None, empty| |M23, None, empty| |N23, None, empty| |O23, None, empty| |P23, None, empty| |Q23, None, empty| |R23, None, empty| |S23, None, empty| |T23, None, empty| |U23, None, empty| |V23, None, empty| |W23, None, empty| |X23, None, empty| |Y23, None, empty| || |A24, Athelas, string| |B24, 33/hr USD, string| |C24, 1200/mo USD housing stipend (2nd coop) + flights, string| |D24, None, empty| |E24, None, empty| |F24, None, empty| |G24, None, empty| |H24, None, empty| |I24, None, empty| |J24, None, empty| |K24, None, empty| |L24, None, empty| |M24, None, empty| |N24, None, empty| |O24, None, empty| |P24, None, empty| |Q24, None, empty| |R24, None, empty| |S24, None, empty| |T24, None, empty| |U24, None, empty| |V24, None, empty| |W24, None, empty| |X24, None, empty| |Y24, None, empty| || |A25, Athos, string| |B25, 5000 USD/mo, string| |C25, None, empty| |D25, None, empty| |E25, None, empty| |F25, None, empty| |G25, None, empty| |H25, None, empty| |I25, None, empty| |J25, None, empty| |K25, None, empty| |L25, None, empty| |M25, None, empty| |N25, None, empty| |O25, None, empty| |P25, None, empty| |Q25, None, empty| |R25, None, empty| |S25, None, empty| |T25, None, empty| |U25, None, empty| |V25, None, empty| |W25, None, empty| |X25, None, empty| |Y25, None, empty| || |A26, Atolio, string| |B26, 34/hr (3rd coop), 38/hr (4th coop), 38/hr (5th coop), 42/hr (6th coop), string| |C26, None, empty| |D26, None, empty| |E26, None, empty| |F26, None, empty| |G26, None, empty| |H26, None, empty| |I26, None, empty| |J26, None, empty| |K26, None, empty| |L26, None, empty| |M26, None, empty| |N26, None, empty| |O26, None, empty| |P26, None, empty| |Q26, None, empty| |R26, None, empty| |S26, None, empty| |T26, None, empty| |U26, None, empty| |V26, None, empty| |W26, None, empty| |X26, None, empty| |Y26, None, empty| || |A27, ATS Corporation, string| |B27, 28/hr (5th year (4B?)), string| |C27, None, empty| |D27, None, empty| |E27, None, empty| |F27, None, empty| |G27, None, empty| |H27, None, empty| |I27, None, empty| |J27, None, empty| |K27, None, empty| |L27, None, empty| |M27, None, empty| |N27, None, empty| |O27, None, empty| |P27, None, empty| |Q27, None, empty| |R27, None, empty| |S27, None, empty| |T27, None, empty| |U27, None, empty| |V27, None, empty| |W27, None, empty| |X27, None, empty| |Y27, None, empty| || |A28, None, empty| |B28, 33/hr (4th coop), string| |C28, None, empty| |D28, 2023, number| |E28, None, empty| |F28, None, empty| |G28, None, empty| |H28, None, empty| |I28, None, empty| |J28, None, empty| |K28, None, empty| |L28, None, empty| |M28, None, empty| |N28, None, empty| |O28, None, empty| |P28, None, empty| |Q28, None, empty| |R28, None, empty| |S28, None, empty| |T28, None, empty| |U28, None, empty| |V28, None, empty| |W28, None, empty| |X28, None, empty| |Y28, None, empty| || |A29, Autodesk, string| |B29, 34/hr (5th coop), string| |C29, None, empty| |D29, 2024, number| |E29, None, empty| |F29, None, empty| |G29, None, empty| |H29, None, empty| |I29, None, empty| |J29, None, empty| |K29, None, empty| |L29, None, empty| |M29, None, empty| |N29, None, empty| |O29, None, empty| |P29, None, empty| |Q29, None, empty| |R29, None, empty| |S29, None, empty| |T29, None, empty| |U29, None, empty| |V29, None, empty| |W29, None, empty| |X29, None, empty| |Y29, None, empty| || |A30, Autonomic, string| |B30, 38-40/hr (4th coop), 41/hr (5th coop), string| |C30, None, empty| |D30, None, empty| |E30, None, empty| |F30, None, empty| |G30, None, empty| |H30, None, empty| |I30, None, empty| |J30, None, empty| |K30, None, empty| |L30, None, empty| |M30, None, empty| |N30, None, empty| |O30, None, empty| |P30, None, empty| |Q30, None, empty| |R30, None, empty| |S30, None, empty| |T30, None, empty| |U30, None, empty| |V30, None, empty| |W30, None, empty| |X30, None, empty| |Y30, None, empty| || |A31, Axonify, string| |B31, 1100/week (4th coop), string| |C31, None, empty| |D31, 2024, number| |E31, None, empty| |F31, None, empty| |G31, None, empty| |H31, None, empty| |I31, None, empty| |J31, None, empty| |K31, None, empty| |L31, None, empty| |M31, None, empty| |N31, None, empty| |O31, None, empty| |P31, None, empty| |Q31, None, empty| |R31, None, empty| |S31, None, empty| |T31, None, empty| |U31, None, empty| |V31, None, empty| |W31, None, empty| |X31, None, empty| |Y31, None, empty| || |A32, Bank of America, string| |B32, 22/hr (2nd coop), string| |C32, None, empty| |D32, None, empty| |E32, None, empty| |F32, None, empty| |G32, None, empty| |H32, None, empty| |I32, None, empty| |J32, None, empty| |K32, None, empty| |L32, None, empty| |M32, None, empty| |N32, None, empty| |O32, None, empty| |P32, None, empty| |Q32, None, empty| |R32, None, empty| |S32, None, empty| |T32, None, empty| |U32, None, empty| |V32, None, empty| |W32, None, empty| |X32, None, empty| |Y32, None, empty| || |A33, Bank of America (Merrill Lynch), string| |B33, 20/hr (1st coop), string| |C33, None, empty| |D33, None, empty| |E33, None, empty| |F33, None, empty| |G33, None, empty| |H33, None, empty| |I33, None, empty| |J33, None, empty| |K33, None, empty| |L33, None, empty| |M33, None, empty| |N33, None, empty| |O33, None, empty| |P33, None, empty| |Q33, None, empty| |R33, None, empty| |S33, None, empty| |T33, None, empty| |U33, None, empty| |V33, None, empty| |W33, None, empty| |X33, None, empty| |Y33, None, empty| || |A34, BDO, string| |B34, 34.36/hr, 25/h (2nd coop), 32/h (3rd coop), string| |C34, None, empty| |D34, None, empty| |E34, None, empty| |F34, None, empty| |G34, None, empty| |H34, None, empty| |I34, None, empty| |J34, None, empty| |K34, None, empty| |L34, None, empty| |M34, None, empty| |N34, None, empty| |O34, None, empty| |P34, None, empty| |Q34, None, empty| |R34, None, empty| |S34, None, empty| |T34, None, empty| |U34, None, empty| |V34, None, empty| |W34, None, empty| |X34, None, empty| |Y34, None, empty| || |A35, Bentley Systems, string| |B35, 30/hr (1st coop), 33/hr (2nd coop), string| |C35, None, empty| |D35, None, empty| |E35, None, empty| |F35, None, empty| |G35, None, empty| |H35, None, empty| |I35, None, empty| |J35, None, empty| |K35, None, empty| |L35, None, empty| |M35, None, empty| |N35, None, empty| |O35, None, empty| |P35, None, empty| |Q35, None, empty| |R35, None, empty| |S35, None, empty| |T35, None, empty| |U35, None, empty| |V35, None, empty| |W35, None, empty| |X35, None, empty| |Y35, None, empty| || |A36, BETS Program, string| |B36, 3000 stipend, string| |C36, None, empty| |D36, None, empty| |E36, None, empty| |F36, None, empty| |G36, None, empty| |H36, None, empty| |I36, None, empty| |J36, None, empty| |K36, None, empty| |L36, None, empty| |M36, None, empty| |N36, None, empty| |O36, None, empty| |P36, None, empty| |Q36, None, empty| |R36, None, empty| |S36, None, empty| |T36, None, empty| |U36, None, empty| |V36, None, empty| |W36, None, empty| |X36, None, empty| |Y36, None, empty| || |A37, BetterUp, string| |B37, 8500/mo, string| |C37, None, empty| |D37, None, empty| |E37, None, empty| |F37, None, empty| |G37, None, empty| |H37, None, empty| |I37, None, empty| |J37, None, empty| |K37, None, empty| |L37, None, empty| |M37, None, empty| |N37, None, empty| |O37, None, empty| |P37, None, empty| |Q37, None, empty| |R37, None, empty| |S37, None, empty| |T37, None, empty| |U37, None, empty| |V37, None, empty| |W37, None, empty| |X37, None, empty| |Y37, None, empty| || |A38, Bitbuy, string| |B38, 20/hr (1st coop), st

In [84]:
df=get_data('evaluation/all_data_912/dataset.json')

In [85]:
print(len(df))

912

In [86]:
import os
def give_sheets_from_dir(dir_path):
    result = {}
    for filename in os.listdir(dir_path):
        if filename.endswith("input.xlsx") or filename.endswith(".xlsm") or filename.endswith(".xltx") or filename.endswith(".xltm"):
            file_path = os.path.join(dir_path, filename)
            identity = filename.strip('_input.xlsx')
            result[file_path] = identity
    return result

print(give_sheets_from_dir("evaluation/all_data_912/spreadsheet/13-1"))

{'evaluation/all_data_912/spreadsheet/13-1/1_13-1_input.xlsx': '1_13-1', 'evaluation/all_data_912/spreadsheet/13-1/3_13-1_input.xlsx': '3_13-1', 'evaluation/all_data_912/spreadsheet/13-1/2_13-1_input.xlsx': '2_13-1'}

In [87]:
import pandas as pd

def expand_spreadsheets(df):
    rows = []
    for _, row in df.iterrows():
        # get dict of {path: identity}
        mapping = give_sheets_from_dir(f"evaluation/all_data_912/{row['spreadsheet_path']}")
        
        # expand into multiple rows
        for path, identity in mapping.items():
            new_row = row.to_dict().copy()
            new_row['new_spreadsheet_path'] = path
            new_row['new_id'] = identity
            rows.append(new_row)
    
    return pd.DataFrame(rows)

# Usage:
df_expanded = expand_spreadsheets(df)
df_expanded.sort_values(by='new_id', inplace=True)
df=df_expanded
df

,id,instruction,spreadsheet_path,instruction_type,answer_position,answer_sheet,data_position,new_spreadsheet_path,new_id
285,102-20,I need guidance with reformatting my Excel raw...,spreadsheet/102-20,Sheet-Level Manipulation,'Raw Data'!B2:I40,Raw Data,"Raw Data!'A1:J19,'Expected result!'A1:J32,",evaluation/all_data_912/spreadsheet/102-20/1_1...,1_102-20
1653,10281,I want to configure column 'J' under 'Densitie...,spreadsheet/10281,Cell-Level Manipulation,J15:J17,NaN,NaN,evaluation/all_data_912/spreadsheet/10281/1_10...,1_10281
1656,10452,I need a method to perform a vertical lookup i...,spreadsheet/10452,Cell-Level Manipulation,E4:E12,NaN,NaN,evaluation/all_data_912/spreadsheet/10452/1_10...,1_10452
1657,10493,I am working on a salary spreadsheet for my wi...,spreadsheet/10493,Cell-Level Manipulation,C8:G11,NaN,NaN,evaluation/all_data_912/spreadsheet/10493/1_10...,1_10493
288,105-13,How can I use VBA to filter data from a multi-...,spreadsheet/105-13,Sheet-Level Manipulation,'Calculation!'C11:I490',"Source,Calculation","Source!'H3:K1964,'Calculation!'B11:R490'",evaluation/all_data_912/spreadsheet/105-13/1_1...,1_105-13
...,...,...,...,...,...,...,...,...,...
958,CF_7938,How can I use conditional formatting to highli...,spreadsheet/CF_7938,Sheet-Level Manipulation,'Sheet1'!C8:I8,Sheet1,B4:J8,evaluation/all_data_912/spreadsheet/CF_7938/3_...,3_CF_7938
963,CF_8276,How can I set up a conditional format to color...,spreadsheet/CF_8276,Sheet-Level Manipulation,'Data'!E2:E8,Data,A1:I4,evaluation/all_data_912/spreadsheet/CF_8276/3_...,3_CF_8276
966,CF_8830,I am needing to highlight cells in red where f...,spreadsheet/CF_8830,Sheet-Level Manipulation,'Sheet1'!B2:B8,Sheet1,A1:A8,evaluation/all_data_912/spreadsheet/CF_8830/3_...,3_CF_8830
969,CF_9945,I need to apply conditional formatting to cell...,spreadsheet/CF_9945,Sheet-Level Manipulation,'Sheet1'!A3:G3,Sheet1,A1:G13,evaluation/all_data_912/spreadsheet/CF_9945/3_...,3_CF_9945
2424,59279,How can I create a formula in Excel to extract...,spreadsheet/59279,Cell-Level Manipulation,B1:B2,NaN,NaN,evaluation/all_data_912/spreadsheet/59279/3__5...,3__59279

In [88]:
print(len(df))

2726

In [89]:
df['context']=df['new_spreadsheet_path'].apply(make_context)
# df['eval_response']=df['context'].apply(eval)

/Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
/Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Slicer List extension is not supported and will be removed
  warn(msg)
/Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openpyxl/reader/drawings.py:33: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/Users/karman/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Sparkline Group extension is not supported and will be removed
  warn(msg)

In [90]:
df

,id,instruction,spreadsheet_path,instruction_type,answer_position,answer_sheet,data_position,new_spreadsheet_path,new_id,context
285,102-20,I need guidance with reformatting my Excel raw...,spreadsheet/102-20,Sheet-Level Manipulation,'Raw Data'!B2:I40,Raw Data,"Raw Data!'A1:J19,'Expected result!'A1:J32,",evaluation/all_data_912/spreadsheet/102-20/1_1...,1_102-20,"{'Raw Data': '|A1, FX Fund, string| |A2, SOI, ..."
1653,10281,I want to configure column 'J' under 'Densitie...,spreadsheet/10281,Cell-Level Manipulation,J15:J17,NaN,NaN,evaluation/all_data_912/spreadsheet/10281/1_10...,1_10281,"{'Sheet1': '|A1, Proctors, string| |A2, Procto..."
1656,10452,I need a method to perform a vertical lookup i...,spreadsheet/10452,Cell-Level Manipulation,E4:E12,NaN,NaN,evaluation/all_data_912/spreadsheet/10452/1_10...,1_10452,"{'Sheet1': '|A1, None, empty| |A2, None, empty..."
1657,10493,I am working on a salary spreadsheet for my wi...,spreadsheet/10493,Cell-Level Manipulation,C8:G11,NaN,NaN,evaluation/all_data_912/spreadsheet/10493/1_10...,1_10493,"{'Sheet1': '|A1, Employee, string| |A2, Jo, st..."
288,105-13,How can I use VBA to filter data from a multi-...,spreadsheet/105-13,Sheet-Level Manipulation,'Calculation!'C11:I490',"Source,Calculation","Source!'H3:K1964,'Calculation!'B11:R490'",evaluation/all_data_912/spreadsheet/105-13/1_1...,1_105-13,"{'Source': '|A1, None, empty| |A2, None, empty..."
...,...,...,...,...,...,...,...,...,...,...
958,CF_7938,How can I use conditional formatting to highli...,spreadsheet/CF_7938,Sheet-Level Manipulation,'Sheet1'!C8:I8,Sheet1,B4:J8,evaluation/all_data_912/spreadsheet/CF_7938/3_...,3_CF_7938,"{'Sheet1': '|A1, None, empty| |A2, None, empty..."
963,CF_8276,How can I set up a conditional format to color...,spreadsheet/CF_8276,Sheet-Level Manipulation,'Data'!E2:E8,Data,A1:I4,evaluation/all_data_912/spreadsheet/CF_8276/3_...,3_CF_8276,"{'Data': '|A1, None, empty| |A2, Fred, string|..."
966,CF_8830,I am needing to highlight cells in red where f...,spreadsheet/CF_8830,Sheet-Level Manipulation,'Sheet1'!B2:B8,Sheet1,A1:A8,evaluation/all_data_912/spreadsheet/CF_8830/3_...,3_CF_8830,"{'Sheet1': '|A1, Vehicle Description, string| ..."
969,CF_9945,I need to apply conditional formatting to cell...,spreadsheet/CF_9945,Sheet-Level Manipulation,'Sheet1'!A3:G3,Sheet1,A1:G13,evaluation/all_data_912/spreadsheet/CF_9945/3_...,3_CF_9945,"{'Sheet1': '|A1, Veke 1, string| |A2, 2022-01-..."
2424,59279,How can I create a formula in Excel to extract...,spreadsheet/59279,Cell-Level Manipulation,B1:B2,NaN,NaN,evaluation/all_data_912/spreadsheet/59279/3__5...,3__59279,"{'Sheet1': '|A1, 240723008147, number| |A2, 19..."

In [91]:
df.to_csv("staging.csv", index=False)